POST http://localhost:8080/create
Content-Type: application/json

{
  "name": "Ivan",
  "age": 25
}

POST http://localhost:8080/create
Content-Type: application/json

{
  "name": "Alex",
  "age": 30
}

POST http://localhost:8080/create
Content-Type: application/json

{
  "name": "Ivan",
  "age": 22
}

POST http://localhost:8080/create
Content-Type: application/json

{
  "name": "Ivan",
  "age": 22
}
